services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    environment:
      - NAME=hansphilemonlimanza

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/db:/app/db
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NAME=hansphilemonlimanza

networks:
  app-network:
    driver: bridge
