services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/db:/app/db
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge